apiVersion: v1
kind: Pod

metadata:
  name: house-price-backend
  namespace: house-price
  
  labels:
    app: house-price-backend


spec:
  containers:
    - name: backend
      image: raviikrds/house-price-backend:latest

      ports:
        - containerPort: 8000
