apiVersion: v1
kind: Service

metadata:
  name: house-price-backend-service
  namespace: house-price

spec:
  selector:
    app: house-price-backend

  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000

  type: ClusterIP